export const areaOptions = [
  { code: "CHH000N1", address: "Chhatrapati Nagar Area 1" },
  { code: "CHH000N2", address: "Chhatrapati Nagar Area 2" },
  { code: "CHH000N3", address: "Chhatrapati Nagar Area 3" },
  { code: "CHH000N4", address: "Chhatrapati Nagar Area 4" },
  { code: "CHH000N5", address: "Chhatrapati Nagar Area 5" },
  { code: "CHH000N6", address: "Chhatrapati Nagar Area 6" },
  { code: "CHH000N7", address: "Chhatrapati Nagar Area 7" },
  { code: "CHH000N8", address: "Chhatrapati Nagar Area 8" },
  { code: "WALUJ001", address: "Waluj Sector 1" },
  { code: "WALUJ002", address: "Waluj Sector 2" },
  { code: "WALUJ003", address: "Waluj Sector 3" },
  { code: "WALUJ004", address: "Waluj Sector 4" },
  { code: "WALUJ005", address: "Waluj Sector 5" },
  { code: "WALUJ006", address: "Waluj Sector 6" },
  { code: "WALUJ007", address: "Waluj Sector 7" },
  { code: "WALUJ008", address: "Waluj Sector 8" },
  { code: "CIDCO001", address: "CIDCO N-1" },
  { code: "CIDCO002", address: "CIDCO N-2" },
  { code: "CIDCO003", address: "CIDCO N-3" },
  { code: "CIDCO004", address: "CIDCO N-4" },
  { code: "CENTRAL0", address: "Central Zone 0" },
  { code: "CENTRAL1", address: "Central Zone 1" },
  { code: "CENTRAL2", address: "Central Zone 2" },
  { code: "CENTRAL3", address: "Central Zone 3" },
  { code: "CENTRAL4", address: "Central Zone 4" },
  { code: "CENTRAL5", address: "Central Zone 5" },
  { code: "CENTRAL6", address: "Central Zone 6" },
  { code: "CENTRAL7", address: "Central Zone 7" },
  { code: "CENTRAL8", address: "Central Zone 8" },
  { code: "CENTRAL9", address: "Central Zone 9" },
  { code: "EAST0001", address: "East Zone 1" },
  { code: "EAST0002", address: "East Zone 2" },
  { code: "EAST0003", address: "East Zone 3" },
  { code: "EAST0004", address: "East Zone 4" },
  { code: "HARSUL01", address: "Harsul Area 1" },
  { code: "HARSUL02", address: "Harsul Area 2" },
  { code: "HARSUL03", address: "Harsul Area 3" },
  { code: "HARSUL04", address: "Harsul Area 4" },
  { code: "SOUTH001", address: "South Zone 1" },
  { code: "SOUTH002", address: "South Zone 2" },
  { code: "SOUTH003", address: "South Zone 3" },
  { code: "SOUTH004", address: "South Zone 4" },
  { code: "WEST0001", address: "West Zone 1" },
  { code: "WEST0002", address: "West Zone 2" },
  { code: "WEST0003", address: "West Zone 3" },
  { code: "WEST0004", address: "West Zone 4" },
  { code: "WEST0005", address: "West Zone 5" },
  { code: "WEST0006", address: "West Zone 6" },
  { code: "WEST0007", address: "West Zone 7" },
  { code: "WEST0008", address: "West Zone 8" },
  { code: "OUTER001", address: "Outer Ring 1" },
  { code: "OUTER002", address: "Outer Ring 2" },
  { code: "OUTER003", address: "Outer Ring 3" },
  { code: "OUTER004", address: "Outer Ring 4" },
  { code: "OUTER005", address: "Outer Ring 5" },
  { code: "OUTER006", address: "Outer Ring 6" },
  { code: "OUTER007", address: "Outer Ring 7" },
  { code: "OUTER008", address: "Outer Ring 8" },
];

export const categoryOptions = [
  "general",
  "e-waste",
  "medical-waste",
  "harmful-waste",
  "non-harmful-dry-waste",
  "non-harmful-wet-waste",
];

export const reasonOptions = [
  "Daily Collection",
  "Scheduled Pickup",
  "Complaint Resolution",
  "Other",
];
